#!/bin/bash
#
# Copyright 2016-present The Material Motion Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Add --trace to every arc unit invocation for travis CI builds.

git checkout . --quiet
git clean -fd --quiet
git checkout origin/develop --quiet
git branch -D develop --quiet
git checkout -b develop origin/develop --quiet

if [ ! -f ".travis.yml" ]; then
  echo "No .travis.yml exists, skipping..."
  exit 0
fi

sed -i.bak -e 's/  - arcanist\/bin\/arc unit --everything$/  - arcanist\/bin\/arc unit --everything --trace/' .travis.yml
rm .travis.yml.bak

git add .
git commit -am "[automated lsc] Add --trace to arc unit invocation for travis builds."
git diff HEAD^...HEAD
echo "Press enter to publish the above diff..."
read
git push origin develop
