#!/bin/bash
#
# Copyright 2016-present The Material Motion Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Removes all third_party and .arc-hook submodules from a repository.

git reset HEAD .
git checkout .
git clean -ffd
git checkout origin/develop
git branch -D develop
git checkout -b develop origin/develop

echo "Removing modules..."
rm -rf third_party/
rm -rf .arc-hooks/
git rm .gitmodules -f
perl -i.bak -pe "s:\"(.+)/(arc-.+)\":\"material-arc-tools/third_party/\2\":g" .arcconfig
rm .arcconfig.bak
perl -i.bak -pe "s:\"(.+)/(clang-format-linter)\":\"material-arc-tools/third_party/\2\":g" .arcconfig
rm .arcconfig.bak

git add .
git commit -am "Automated large-scaled change: removed all submodules."
git diff HEAD^...HEAD
echo "Press enter to publish the above diff..."
read
git push origin develop
